.global: &global
  only:
    refs:
      - branches
    changes:
      - .gitlab-ci.yml
      - ./*.go
  before_script:
    - go version
    - go env

.amd64: &amd64
  variables:
    VGOOS: linux
    VGOARCH: amd64

.i386: &i386
  variables:
    VGOOS: linux
    VGOARCH: 386

.unit.test.script: &script
  script:
    - GOOS=${VGOOS} GOARCH=${VGOARCH} go test -v

.unit.test.script.cover: &script_cover
  script:
    - GOOS=${VGOOS} GOARCH=${VGOARCH} go test -cover -v

go.1.2 unit.test 1/2:
  <<: [*global, *script, *amd64]
  image: golang:1.2

go.1.2 unit.test 2/2:
  <<: [*global, *script, *i386]
  image: golang:1.2-cross

go.1.3 unit.test 1/2:
  <<: [*global, *script, *amd64]
  image: golang:1.3

go.1.3 unit.test 2/2:
  <<: [*global, *script, *i386]
  image: golang:1.3-cross

go.1.4 unit.test 1/2:
  <<: [*global, *script_cover, *amd64]
  image: golang:1.4-alpine
  before_script:
    - go version
    - go env
    - apk add --no-cache git
    - go get golang.org/x/tools/cmd/cover

go.1.4 unit.test 2/2:
  <<: [*global, *script_cover, *i386]
  image: golang:1.4-cross
  before_script:
    - go version
    - go env
    - apt-get install -y git
    - go get golang.org/x/tools/cmd/cover

go.1.5 unit.test 1/2:
  <<: [*global, *script_cover, *amd64]
  image: golang:1.5-alpine

go.1.5 unit.test 2/2:
  <<: [*global, *script_cover, *i386]
  image: golang:1.5-alpine

go.1.6 unit.test 1/2:
  <<: [*global, *script_cover, *amd64]
  image: golang:1.6-alpine

go.1.6 unit.test 2/2:
  <<: [*global, *script_cover, *i386]
  image: golang:1.6-alpine

go.1.7 unit.test 1/2:
  <<: [*global, *script_cover, *amd64]
  image: golang:1.7-alpine

go.1.7 unit.test 2/2:
  <<: [*global, *script_cover, *i386]
  image: golang:1.7-alpine

go.1.8 unit.test 1/2:
  <<: [*global, *script_cover, *amd64]
  image: golang:1.8-alpine

go.1.8 unit.test 2/2:
  <<: [*global, *script_cover, *i386]
  image: golang:1.8-alpine

go.1.9 unit.test 1/2:
  <<: [*global, *script_cover, *amd64]
  image: golang:1.9-alpine

go.1.9 unit.test 2/2:
  <<: [*global, *script_cover, *i386]
  image: golang:1.9-alpine

go.1.10 unit.test 1/2:
  <<: [*global, *script_cover, *amd64]
  image: golang:1.10-alpine

go.1.10 unit.test 2/2:
  <<: [*global, *script_cover, *i386]
  image: golang:1.10-alpine

go.1.11 unit.test 1/2:
  <<: [*global, *script_cover, *amd64]
  image: golang:1.11-alpine

go.1.11 unit.test 2/2:
  <<: [*global, *script_cover, *i386]
  image: golang:1.11-alpine

go.1.12 unit.test 1/2:
  <<: [*global, *script_cover, *amd64]
  image: golang:1.12-alpine

go.1.12 unit.test 2/2:
  <<: [*global, *script_cover, *i386]
  image: golang:1.12-alpine
