.unit.test.script.cover: &script
  only:
  - branches
  script:
    go test -cover -v

unit.test go.1.4:
  image: golang:1.4-alpine
  before_script:
  - apk add --no-cache git
  - go get golang.org/x/tools/cmd/cover
  <<: *script

unit.test go.1.5:
  image: golang:1.5-alpine
  <<: *script

unit.test go.1.6:
  image: golang:1.6-alpine
  <<: *script

unit.test go.1.7:
  image: golang:1.7-alpine
  <<: *script

unit.test go.1.8:
  image: golang:1.8-alpine
  <<: *script

unit.test go.1.9:
  image: golang:1.9-alpine
  <<: *script

unit.test go.1.10:
  image: golang:1.10-alpine
  <<: *script

unit.test go.1.11:
  image: golang:1.11-alpine
  <<: *script
